from .populate_document_type import populate_document_type
from .populate_geography import populate_geography
from .populate_language import populate_language
from .populate_source import populate_source
from .populate_geo_statistics import populate_geo_statistics
