version: '3.7'
services:
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    build: ./e2e
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://localhost:3000
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    network_mode: 'host'
    volumes:
      - ./e2e:/e2e

volumes:
  db-data:
