version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - "postgres"

  loader:
    build:
      context: loader
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./loader:/app/:cached
    environment:
      PYTHONPATH: .
      DATA_DIR: /app/data
      ENV: production
    env_file:
      - .env
    depends_on:
      - backend

  frontend:
    #    user: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: development
    command: npm run dev
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/opt/node_app/app
      # bind-mounting these two files in will let you add packages during development without rebuilding.
      # Add the dependency inside the container with:
      #
      # docker-compose exec -w /opt/node_app frontend npm install --save <package name>
      # docker-compose exec -w /opt/node_app frontend npm install --save-dev <package name>
      #
      # and then nextjs will restart. Your changes will last until you "docker-compose down" and will
      # be saved on host for next build.
      - ./frontend/package.json:/opt/node_app/package.json
      - ./frontend/package-lock.json:/opt/node_app/package-lock.json
      # this is a workaround to prevent host node_modules from accidentally getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /app/node_modules location.
      - ./notused:/opt/node_app/app/node_modules

  search-index:
    build:
      context: .
      dockerfile: search-index/Dockerfile
    tty: true
    volumes:
      - ./search-index:/app/:cached
    environment:
      PYTHONPATH: .
      ENV: production
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - opensearch-node1

  opensearch-node1:
    image: opensearchproject/opensearch:1.3.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    
volumes:
  db-data:
  opensearch-data1:
