repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: [ "toml" ]
  - repo: local
    hooks:
      - id: pyright
        name: pyright (backend)
        entry: pyright
        language: node
        files: ^backend/
        types: [python]
        additional_dependencies: ['pyright@1.1.267']

# TODO bandit?, safety?, snyk?
