config:
  aws:region: eu-west-2
  infra:backend_secret_key:
    secure: AAABACHowsD8gf29n/r7wilcbfElQTf/wuSBzjlULqSEP+yrlRPN74ABwNMaeDI75CL9VqW4Ofvnj02Y19k6HjhJ4QM=
  infra:db_password:
    secure: AAABAIOgwzKhKiupZ2A3xljVNX7VZ2I/iBioWlqt66auYjiE3JkfsbMQzhOt6rp7L5RDwdwTLyGTUoRK
  infra:db_username: navigator_db_user
