config:
  aws:region: eu-west-2
  infra:backend_secret_key:
    secure: AAABAP6pXDnXJ6797mY5GmEUnzPb1nVXGwetzQQijjWHI2NWEPovAPVA9ZVOA0rfWb8UsEvXMSRuEtwHZWiKIBr3rnk=
  infra:db_password:
    secure: AAABAOlREzULzg9AkORtP2wNLSN0FLmc6uuPkOSt4pgkRANU4/bMQYyJ4CL5+Aj1zU2GdRQ3niyldmEUT4Q/XPV/gRcdkHXGrEFWOzpbSro=
  infra:db_username: navigator_db_user
  infra:dev_domain: dev.app.climatepolicyradar.org
  infra:dev_pdf_embed_key:
    secure: AAABAHguBbfjL8Z+j/ptGWk4BjJ43+RAQeQZfWSh6l51uPov+prNuSkUpo2tqGJTDMwa6+PLGHpOYAWIbedHzQ==
  infra:opensearch_password:
    secure: AAABACOeZAXubeoFLu8Vo83fqorH9sjVyGoBhuZPGLEIpdmiEdFQv0WqjTE=
  infra:opensearch_url: https://search-opensearch-dev-temp-nzkttufrxxmadvl37l4teezwri.eu-west-2.es.amazonaws.com
  infra:opensearch_user: cpr-master
  infra:prod_domain: app.climatepolicyradar.org
  infra:prod_pdf_embed_key:
    secure: AAABAI0KrfHW8Q5cRhg6iTPrYrSljSq3+RYZo3NdJXUQuCV076e89ILmrV4ENvrKmstPv/ZJ7z+S5M/id+Ybmw==
  infra:sendgrid_api_token:
    secure: AAABAOdYi9vQCHT8oWxCM0r4jB2y0QCLuW14t+X2ngUoWQ83iU+BDzJwuZySy2KDCTLKLozHkxJy99Vklm00FW5W98QDfaB5xieSHlkaNeZTKFgGNa/bbcTp3RqvRoP9BVa1idA=
  infra:sendgrid_enabled: "True"
  infra:sendgrid_from_email:
    secure: AAABAAUz13vgcjUK/1t5VU7Hy7/EYKkKtB8Gv16H+ZDtA0XJo1VE9unvxRG4H6bKASx2WpsYmTq7Jcbvvxg=
  infra:slack_webhook_url:
    secure: AAABAH9/ZhhD9I7pmDg3WSK2z6lCigqE3/DsYxtfvsvmICCRela3rHfDRFAw61XmX3DgugZyUr+YF7js8G64206HC1CUJ2qOD65V8udGbAmP5V+rWdJ2H3XBFDR9CKygepzGmPCbCV5m90PONHnaJNM=
