export const partners = [
  {
    name: 'LSE logo',
    logo: 'lse-logo.png',
    link: 'https://www.lse.ac.uk/',
    height: '235',
    width: '240',
  },
  {
    name: 'Grantham Reasearch Institute on Climate Change and the Environment logo',
    logo: 'grantham-logo.png',
    link: 'https://www.lse.ac.uk/granthaminstitute/',
    height: '696',
    width: '180',
  },
  {
    name: 'WORLD Policy Analysis Center logo',
    logo: 'world-policy-logo.png',
    link: 'https://www.worldpolicycenter.org/about/about-world',
    height: '400',
    width: '292',
  },
  {
    name: 'The World Bank logo',
    logo: 'world-bank-logo.png',
    link: 'https://www.worldbank.org/en/home',
    height: '608',
    width: '110',
  },
  {
    name: 'South South North logo',
    logo: 'south-south-north-logo.png',
    link: 'https://southsouthnorth.org/',
    height: '280',
    width: '236',
  },
  {
    name: 'Climate & Development Knowledge Network logo',
    logo: 'cdkn-logo.png',
    link: 'https://cdkn.org/',
    height: '539',
    width: '232',
  },
  {
    name: 'DLA Piper UK LLP logo',
    logo: 'dla-piper-logo.png',
    link: 'http://www.dlapiper.com/',
    height: '790',
    width: '462',
  },
  {
    name: 'Adobe logo',
    logo: 'adobe-logo.png',
    link: 'https://www.adobe.com/',
    height: '720',
    width: '188',
  },
];
