"""Add geo_statistics

Revision ID: 0002
Revises: 0001
Create Date: 2022-08-02 11:12:29.678568
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_statistics",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("geography_id", sa.Integer(), nullable=False),
        sa.Column("legislative_process", sa.Text(), nullable=False),
        sa.Column("federal", sa.Boolean(), nullable=False),
        sa.Column("federal_details", sa.Text(), nullable=False),
        sa.Column("political_groups", sa.Text(), nullable=False),
        sa.Column("global_emissions_percent", sa.Float(), nullable=True),
        sa.Column("climate_risk_index", sa.Float(), nullable=True),
        sa.Column("worldbank_income_group", sa.Text(), nullable=False),
        sa.Column("visibility_status", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["geography_id"],
            ["geography.id"],
            name=op.f("fk_geo_statistics__geography_id__geography"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geo_statistics")),
        sa.UniqueConstraint("name", name=op.f("uq_geo_statistics__name")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("geo_statistics")
    # ### end Alembic commands ###
