"""add unique constraint to language code

Revision ID: 0004
Revises: 0003
Create Date: 2022-04-19 16:04:09.999191

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_language__language_code"), "language", ["language_code"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_language__language_code"), "language", type_="unique")
    # ### end Alembic commands ###
