"""add uniqeness constraint to action

Revision ID: 0005
Revises: 0004
Create Date: 2022-02-18 11:03:35.999424

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_action__name"),
        "action",
        ["name", "action_date", "geography_id", "action_type_id", "action_source_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_action__name"), "action", type_="unique")
    # ### end Alembic commands ###
