"""allow_document_md5sum_nullable

Revision ID: 0005
Revises: 0004
Create Date: 2022-09-28 11:08:02.176237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "md5_sum", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "md5_sum", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
