"""change action description column length from 2048 to max

Revision ID: 0006
Revises: 0005
Create Date: 2022-02-25 16:24:19.792970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "action",
        "description",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.Text,
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "action",
        "description",
        existing_type=sa.Text,
        type_=sa.VARCHAR(length=2048),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
