"""change action name column length from 2048 to max

Revision ID: 0007
Revises: 0006
Create Date: 2022-02-25 17:38:16.694570

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'name',
                    existing_type=sa.VARCHAR(length=2048),
                    type_=sa.Text,
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'name',
                    existing_type=sa.Text,
                    type_=sa.VARCHAR(length=2048),
                    existing_nullable=False)
    # ### end Alembic commands ###
