"""add enum to document to represent validity

Revision ID: 0008
Revises: 0007
Create Date: 2022-03-02 18:01:14.393573

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None

document_invalid_reason = postgresql.ENUM(
    "unsupported_content_type",
    "net_ssl_error",
    "net_read_error",
    "net_connection_error",
    "net_too_many_redirects",
    name="document_invalid_reason",
)


def upgrade():
    document_invalid_reason.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("is_valid", sa.Boolean(), nullable=False))
    op.add_column(
        "document",
        sa.Column(
            "invalid_reason",
            sa.Enum(
                "unsupported_content_type",
                "net_ssl_error",
                "net_read_error",
                "net_connection_error",
                "net_too_many_redirects",
                name="document_invalid_reason",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "invalid_reason")
    op.drop_column("document", "is_valid")
    # ### end Alembic commands ###
    document_invalid_reason.drop(op.get_bind())
