"""change category from multi to single relationship

Revision ID: 0008
Revises: 0007
Create Date: 2022-05-03 09:58:39.936352

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_category")
    op.add_column("document", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_document__category_id__category"),
        "document",
        "category",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_document__category_id__category"), "document", type_="foreignkey"
    )
    op.drop_column("document", "category_id")
    op.create_table(
        "document_category",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("document_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name="fk_document_category__document_id__document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["category.id"], name="fk_document_category__type_id__category"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_document_category"),
    )
    # ### end Alembic commands ###
