"""import id and slug unique and not null

Revision ID: 0008
Revises: 0007
Create Date: 2022-10-27 14:20:03.341487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "slug", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("document", "import_id", existing_type=sa.TEXT(), nullable=False)
    op.create_index(
        op.f("ix_document_import_id"), "document", ["import_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_import_id"), table_name="document")
    op.alter_column("document", "import_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("document", "slug", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
