"""add extra user fields

Revision ID: 0009
Revises: 0008
Create Date: 2022-03-25 15:25:12.468772

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("names", sa.String(), nullable=True))
    op.add_column("user", sa.Column("job_role", sa.String(), nullable=True))
    op.add_column("user", sa.Column("location", sa.String(), nullable=True))
    op.add_column(
        "user", sa.Column("affiliation_organisation", sa.String(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("affiliation_type", sa.ARRAY(sa.Text()), nullable=True)
    )
    op.add_column(
        "user", sa.Column("policy_type_of_interest", sa.ARRAY(sa.Text()), nullable=True)
    )
    op.add_column(
        "user", sa.Column("geographies_of_interest", sa.ARRAY(sa.Text()), nullable=True)
    )
    op.add_column(
        "user", sa.Column("data_focus_of_interest", sa.ARRAY(sa.Text()), nullable=True)
    )
    op.drop_column("user", "first_name")
    op.drop_column("user", "last_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("user", "data_focus_of_interest")
    op.drop_column("user", "geographies_of_interest")
    op.drop_column("user", "policy_type_of_interest")
    op.drop_column("user", "affiliation_type")
    op.drop_column("user", "affiliation_organisation")
    op.drop_column("user", "location")
    op.drop_column("user", "job_role")
    op.drop_column("user", "names")
    # ### end Alembic commands ###
