"""extend unique constraint on instrument and sector

Revision ID: 0009
Revises: 0008
Create Date: 2022-05-03 17:25:26.287757

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_instrument__name", "instrument", type_="unique")
    op.create_unique_constraint(
        op.f("uq_instrument__name"), "instrument", ["name", "source_id", "parent_id"]
    )
    op.drop_constraint("uq_sector__name", "sector", type_="unique")
    op.create_unique_constraint(
        op.f("uq_sector__name"), "sector", ["name", "source_id", "parent_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_sector__name"), "sector", type_="unique")
    op.create_unique_constraint("uq_sector__name", "sector", ["name", "source_id"])
    op.drop_constraint(op.f("uq_instrument__name"), "instrument", type_="unique")
    op.create_unique_constraint(
        "uq_instrument__name", "instrument", ["name", "source_id"]
    )
    # ### end Alembic commands ###
