"""add-title-postfix

Revision ID: 0009
Revises: 0008
Create Date: 2022-11-04 14:54:11.315742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("postfix", sa.Text(), nullable=True))
    op.drop_constraint("uq_document__name", "document", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_document__name",
        "document",
        ["name", "geography_id", "type_id", "source_id", "source_url"],
    )
    op.drop_column("document", "postfix")
    # ### end Alembic commands ###
