"""add geography slugs

Revision ID: 0009
Revises: 0008
Create Date: 2022-10-27 16:31:36.602058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("geography", sa.Column("slug", sa.Text(), nullable=False))
    op.alter_column(
        "geography", "display_value", existing_type=sa.TEXT(), nullable=False
    )
    op.create_index(op.f("ix_geography_slug"), "geography", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geography_slug"), table_name="geography")
    op.alter_column(
        "geography", "display_value", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_column("geography", "slug")
    # ### end Alembic commands ###
