"""add md5sum to document

Revision ID: 0012
Revises: 0011
Create Date: 2022-05-06 09:46:27.884121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("md5_sum", sa.Text(), nullable=False))
    op.alter_column("document", "source_url", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("document", "url", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "url", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("document", "source_url", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("document", "md5_sum")
    # ### end Alembic commands ###
