"""add publication date to document

Revision ID: 0014
Revises: 0013
Create Date: 2022-05-11 12:00:42.046266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document", sa.Column("publication_ts", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "publication_ts")
    # ### end Alembic commands ###
