name: run-tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack using .env.example
        run: cp .env.example .env && make start
      - name: verify backend is up
        run: curl http://localhost:8000/api/docs
      - name: Run backend tests
        run: make test_backend && make test_backend_search
      - name: docker
        run: |
          docker-compose logs
          docker-compose ps
          docker ps -a
          ls -la
      - name: verify frontend is up
        run: curl http://localhost:3000
      - name: Configure frontend test env
        run: cp frontend/e2e/.env.example frontend/e2e/.env
      - name: Run frontend tests
        run: make test_frontend
      - name: Log Dump
        run: docker-compose logs
                
  test_loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack using .env.example
        run: cp .env.example .env
      - name: Build
        run: make build_loader
      - name: Test
        run: make test_loader
      - name: Log Dump
        run: docker-compose logs