name: run-tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
# https://github.com/marketplace/actions/docker-layer-caching
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Pull the latest image to build, and avoid caching pull-only images.
        # (docker pull is faster than caching in most cases.)
      - name: Pull images
        run: docker-compose pull

        # In this step, this action saves a list of existing images,
        # the cache is created without them in the post run.
        # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build docker-compose stack using .env.example
        run: cp .env.example .env && make start
      - name: verify backend is up
        run: curl http://localhost:8000/api/docs
      - name: Run backend tests
        run: make test_backend && make test_backend_search
      - name: docker
        run: |
          docker-compose logs
          docker-compose ps
          docker ps -a
          ls -la
      - name: verify frontend is up
        run: curl http://localhost:3000
      - name: Configure frontend test env
        run: cp frontend/e2e/.env.example frontend/e2e/.env
      - name: Run frontend tests
        run: make test_frontend
      - name: Log Dump
        if: always()
        run: docker-compose logs
